### ISSUE TITLE
CT api mismatches present

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#136]
```
molarity : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:290:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:174:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io/js/phetioEngine.js?:138:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Action.js?:254:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:60:21)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/joist/js/Sim.js?:845:50
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
molarity : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:290:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:174:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io/js/phetioEngine.js?:138:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Action.js?:254:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:60:21)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/joist/js/Sim.js?:845:50
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
molarity : phet-io-tests : assert
7 out of 9 tests passed. 2 failed.
SimTests: molarity: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: molarity: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
molarity : phet-io-tests : no-assert
7 out of 9 tests passed. 2 failed.
SimTests: molarity: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: molarity: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

molarity.general.utteranceQueue:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusinAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.focusoutAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.clickAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.inputAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.changeAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keydownAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.controller.input.keyupAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.enabledProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.firedEmitter:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.pressAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pressListener.releaseAction:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.visibleProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.pickableProperty:  3. Any registered PhetioObject must be included in the schema,
molarity.general.navigationBar.a11yButtonsHBox.keyboardHelpButton.opacityProperty:  3. Any registered PhetioObject must be included in the schema,9. Types in the sim must exactly match types in the types file to ensure that type changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
```

**Comment by zepumph** [comment]
This was caused by https://github.com/phetsims/molarity/issues/131. @twant it may be good to add a phet-io test to your pre-commit tests. I recommend either "studio" or "Standalone" from phetmarks. The above "api mismatches present" error can be solved by running `grunt update`. I'm happy to discuss further at our meeting. Over to you to review.

**Comment by zepumph** [comment]
@twant  feel free to close. I just wanted to explain this (which we largely did last meeting). Let me know if you need anything else.

**Comment by twant** [comment]
Okay, thanks @zepumph, and thanks for explaining!
