### ISSUE TITLE
Maximum call stack size exceeded in generating string types

### ISSUE THREAD

**Issue by samreid** [phetsims/molarity#240]
```
  at visit (/Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:289:26)
  at /Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:294:9
  at Array.forEach (<anonymous>:null:null)
  at visit (/Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:289:26)
  at /Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:294:9
  at Array.forEach (<anonymous>:null:null)
  at visit (/Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:289:26)
  at getStringTypes (/Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:298:3)
  at createStringModule (/Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:265:22)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at modulify (/Users/samreid/apache-document-root/main/chipper/js/grunt/modulify.js:347:5)
  at /Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:492:5
  at wrap (/Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:56:7)

Full Error details:
RangeError: Maximum call stack size exceeded
```

**Comment by samreid** [comment]
Duplicate of https://github.com/phetsims/chipper/issues/1170, closing.
